worker_processes auto;

events {
    worker_connections 1024;
}

http {

    proxy_cache_path /var/cache/nginx/cache levels=1:2
        keys_zone=reports_cache:500m
        max_size=5g
        inactive=7d
        use_temp_path=off;

    proxy_temp_path /var/cache/nginx/tmp;

    log_format cdn_log '$remote_addr [$time_local] '
                       '$request $status $body_bytes_sent '
                       'cache:$upstream_cache_status user:$upstream_http_x_user_email';

    access_log /var/log/nginx/access.log cdn_log;
    error_log /var/log/nginx/error.log warn;

    server {
        listen 80;
        server_name _;

        location = /auth {
            internal;
            proxy_pass http://bionicpro-auth:3010/validate;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            # Передаём cookie/headers чтобы auth-service мог определить пользователя
            proxy_set_header Cookie $http_cookie;
            proxy_set_header X-User-Email $http_x_user_email;
            proxy_set_header X-Original-URI $request_uri;
            # Заголовок X-User-Email должен быть возвращён backend’ом
        }

        location /purge/ {
    # Проверка токена (разрешено)
            if ($http_x_internal_token != "secret-internal-token") {
                return 403;
            }

            proxy_cache_key "$scheme$proxy_host$request_uri";

            proxy_cache reports_cache;
            proxy_cache_bypass 1;
            proxy_no_cache 1;

            return 200 "Purged";
        }

        location /reports/ {
            # add_header Access-Control-Allow-Origin "http://localhost:3000";
            # add_header Access-Control-Allow-Credentials true always;
            # add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-User-Email" always;
            # add_header Access-Control-Allow-Methods "GET, OPTIONS" always;

            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Origin "http://localhost:3000";
                add_header Access-Control-Allow-Credentials true;
                add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-User-Email";
                add_header Access-Control-Allow-Methods "GET, OPTIONS";
                return 204;
            }

            auth_request /auth;
            proxy_pass http://minio:9000;

            proxy_cache reports_cache;
            proxy_cache_valid 200 10m;
            proxy_cache_methods GET;
            proxy_cache_use_stale error timeout updating;

                        # CORS для GET/POST
            add_header Access-Control-Allow-Origin "http://localhost:3000";
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-User-Email";
            add_header Access-Control-Allow-Methods "GET, OPTIONS";

            add_header Cache-Control "public, max-age=600" always;
            add_header X-Cache-Status $upstream_cache_status;


            proxy_pass_request_headers on;
            proxy_set_header Host $host;
            proxy_request_buffering off;
            proxy_buffering on;
            proxy_buffers 16 512k;
            proxy_busy_buffers_size 1m;

                # Скрываем дублирующийся заголовок от upstream
            proxy_hide_header Access-Control-Allow-Origin;
            proxy_hide_header Access-Control-Allow-Credentials;
        }

        location = /forbidden {
            return 403;
        }

        location / {
            return 403;
        }
    }
}
