name=crm-connector
connector.class=io.debezium.connector.postgresql.PostgresConnector
plugin.name=pgoutput

database.hostname=crm-db
database.port=5432
database.user=crm_user
database.password=crm_password
database.dbname=crm

database.server.name=crm_server
topic.prefix=crm

slot.name=debezium_slot
publication.name=crm_pub

table.include.list=public.customers

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
key.converter.schemas.enable=false

tombstones.on.delete=false
