name=telemetry-connector
connector.class=io.debezium.connector.postgresql.PostgresConnector
plugin.name=pgoutput

database.hostname=telemetry_db
database.port=5432
database.user=airflow
database.password=airflow
database.dbname=telemetry

database.server.name=telemetry_server
topic.prefix=telemetry

slot.name=debezium_slot
publication.name=telemetry_pub

table.include.list=public.telemetry

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
key.converter.schemas.enable=false

tombstones.on.delete=false
